services:
  - type: web
    name: chemview-backend
    env: python
    plan: free

    buildCommand: |
      pip install -r core/requirements.txt
      python core/manage.py collectstatic --noinput
      python core/manage.py migrate

    startCommand: gunicorn core.core.wsgi:application

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.core.settings

      - key: PYTHON_VERSION
        value: 3.11.4
